//A router is a device that connects two or more packet-switched networks or subnetworks. It serves two primary functions: managing traffic between these networks by forwarding data packets to their intended IP addresses, and allowing multiple devices to use the same Internet connection.
/*How router works step by step?
Let's step through the process of routing a packet from a source to a destination.
Step 1: Send packet to router. Computers send the first packet to the nearest router. ...
Step 2: Router receives packet. ...
Step 3: Router forwards packet. ...
Step 4: Final router forwards message.*/

